package com.mpdc4gsr.component.shared.app.config

object ExtraKeyConfig {
    const val IS_PICK_REPORT_IMG = "IS_PICK_REPORT_IMG"
    const val IS_VIDEO = "IS_VIDEO"
    const val HAS_BACK_ICON = "HAS_BACK_ICON"
    const val CAN_SWITCH_DIR = "CAN_SWITCH_DIR"
    const val IS_TC007 = "IS_TC007"
    const val IS_PICK_INSPECTOR = "IS_PICK_INSPECTOR"
    const val IS_REPORT = "IS_REPORT"
    const val DIR_TYPE = "CUR_DIR_TYPE"
    const val CURRENT_ITEM = "CURRENT_ITEM"
    const val DETECT_ID = "DETECT_ID"
    const val DIR_ID = "DIR_ID"
    const val LONG_ID = "LONG_ID"
    const val URL = "URL"
    const val FILE_ABSOLUTE_PATH = "FILE_ABSOLUTE_PATH"
    const val ITEM_NAME = "ITEM_NAME"
    const val RESULT_INPUT_TEXT = "RESULT_INPUT_TEXT"
    const val RESULT_IMAGE_PATH = "RESULT_IMAGE_PATH"
    const val RESULT_PATH_WHITE = "RESULT_PATH_WHITE"
    const val RESULT_PATH_BLACK = "RESULT_PATH_BLACK"
    const val IMAGE_PATH_LIST = "IMAGE_PATH_LIST"
    const val IMAGE_TEMP_BEAN = "IMAGE_TEMP_BEAN"
    const val REPORT_BEAN = "REPORT_BEAN"
    const val REPORT_INFO = "REPORT_INFO"
    const val REPORT_CONDITION = "REPORT_CONDITION"
    const val REPORT_IR_LIST = "REPORT_IR_LIST"
    const val CUSTOM_PSEUDO_BEAN = "CUSTOM_PSEUDO_BEAN"
    const val TIME_MILLIS = "TIME_MILLIS"
    const val MONITOR_TYPE = "MONITOR_TYPE"
    const val IR_PATH = "ir_path"
    const val TEMP_HIGH = "temp_high"
    const val TEMP_LOW = "temp_low"
    const val IS_CAR_DETECT_ENTER = "IS_CAR_DETECT_ENTER"
    const val reportId = "REPORT_ID"
}


