package com.mpdc4gsr.libunified.app.matrix

object ResultCode {
    val TAG = "mobilelibrary"
    val READY_CONNECT_DEVICE = 1
    val SUCC_FIND_MATCHED_DEVICE = 2
    val SUCC_FIND_DEVICE_INTERFACE = 3
    val SUCC_CONNECT_INTERFACE = 4
    val SUCC_FIND_ENDPOINT = 5
    val SUCC_USB_SEND_CMD = 6
    val ERROR_FIND_DEVICE_NOT_MATCH = -100
    val ERROR_NOT_FIND_DEVICE = -101
    val ERROR_NOT_FIND_INTERFACE = -102
    val ERROR_OPEN_DEVICE_FAILD = -103
    val ERROR_CONNECT_DEVICE_FAILD = -104
    val ERROR_FIND_ENDPOINT_FAILD = -105
    val ERROR_USE_NOT_AGRREN_PERMISSIONS = -106
    val ERROR_USE_USB_ISVALID = -107
    val ERROE_USB_SEND_CMD_FAILD = -108
}