package com.mpdc4gsr.lib.core.http.ts004

object TS004URL {
    const val RTSP_URL = "rtsp://192.168.40.1/ch0/stream0"
    private const val BASE_URL = "http://192.168.40.1:8080"
    const val SET_PSEUDO_COLOR = "$BASE_URL/api/v1/system/setPseudoColor" 
    const val GET_PSEUDO_COLOR = "$BASE_URL/api/v1/system/getPseudoColor" 
    const val SET_PANEL_PARAM = "$BASE_URL/api/v1/system/setPanelParam" 
    const val GET_PANEL_PARAM = "$BASE_URL/api/v1/system/setPanelParam" 
    const val SET_PIP = "$BASE_URL/api/v1/system/setPip" 
    const val GET_PIP = "$BASE_URL/api/v1/system/getPip" 
    const val SET_ZOOM = "$BASE_URL/api/v1/system/setZoom" 
    const val GET_ZOOM = "$BASE_URL/api/v1/system/getZoom" 
    const val SET_SNAPSHOT = "$BASE_URL/api/v1/system/snapshot" 
    const val GET_VRECORD = "$BASE_URL/api/v1/system/vrecord" 
    const val GET_RECORD_STATUS = "$BASE_URL/api/v1/system/getRecordStatus" 
    const val GET_VERSION = "$BASE_URL/api/v1/system/getVersion" 
    const val GET_DEVICE_DETAILS = "$BASE_URL/api/v1/system/getDeviceInfo" 
    const val GET_FREE_SPACE = "$BASE_URL/api/v1/system/getFreeSpace" 
    const val GET_FORMAT_STORAGE = "$BASE_URL/api/v1/system/formatStorage" 
    const val GET_RESET_ALL = "$BASE_URL/api/v1/system/resetAll" 
    const val GET_DELETE_FILE = "$BASE_URL/api/v1/system/deleteFile" 
    const val GET_UPGRADE_STATUS = "$BASE_URL/api/v1/system/getUpgradeStatus" 
    const val SET_TEMPERATURE_STATE =
        "$BASE_URL/api/v1/system/setTemperatureState" 
    const val GET_FILE_LIST = "$BASE_URL/api/v1/system/getFileList" 
    const val SET_DATE_TIME = "$BASE_URL/api/v1/system/setDateTime" 
    const val GET_SEND_UPGRADE_FILE_START =
        "$BASE_URL/api/v1/system/sendUpgradeFileStart" 
    const val GET_SEND_UPGRADE_FILE_DATA = "$BASE_URL/api/v1/system/sendUpgradeFileData" 
    const val GET_SEND_UPGRADE_FILE_END = "$BASE_URL/api/v1/system/sendUpgradeFileEnd" 
    const val GET_REMOTE_UPGRADE = "$BASE_URL/api/v1/system/remoteUpgrade" 
    const val SET_WIFI_AP_ON_OFF = "$BASE_URL/api/v1/system/setWifiAPOnOff" 
    const val GET_WIFI_AP_CONFIG =
        "$BASE_URL/api/v1/system/getWifiAPConfig" 
    const val GET_FILE_COUNT = "$BASE_URL/api/v1/system/getFileCount" 
    const val SET_POWER_ACTION = "$BASE_URL/api/v1/system/setPowerAction" 
    const val SET_DO_NUC = "$BASE_URL/api/v1/system/doNuc" 
    const val SET_FREEZE = "$BASE_URL/api/v1/system/setFreeze" 
    const val GET_BATTERY_INFO = "$BASE_URL/api/v1/system/getBatteryInfo" 
    const val SET_TISP = "$BASE_URL/api/v1/system/setTISR" 
    const val GET_TISR = "$BASE_URL/api/v1/system/getTISR" 
    const val GET_DATE_TIME = "$BASE_URL/api/v1/system/getDateTime" 
}
