package com.mpdc4gsr.libunified.app.utils
import com.mpdc4gsr.libunified.R
import com.mpdc4gsr.libunified.app.BaseApplication
import com.mpdc4gsr.libunified.app.bean.CarDetectBean
import com.mpdc4gsr.libunified.app.bean.CarDetectChildBean
object CarDetectData {
    @JvmStatic
    fun getDetectList(): MutableList<CarDetectBean> {
        val dataList: MutableList<CarDetectBean> = ArrayList()
        val data1List: MutableList<CarDetectChildBean> = ArrayList()
        val data2List: MutableList<CarDetectChildBean> = ArrayList()
        data1List.add(
            CarDetectChildBean(
                0,
                0,
                BaseApplication.instance.getString(R.string.abnormal_description1),
                BaseApplication.instance.getString(R.string.abnormal_item1),
                "40~70",
            ),
        )
        data1List.add(
            CarDetectChildBean(
                0,
                1,
                BaseApplication.instance.getString(R.string.abnormal_description2),
                BaseApplication.instance.getString(R.string.abnormal_item2),
                "200~400",
            ),
        )
        data1List.add(
            CarDetectChildBean(
                0,
                2,
                BaseApplication.instance.getString(R.string.abnormal_description3),
                BaseApplication.instance.getString(R.string.abnormal_item3),
                "200~400",
            ),
        )
        data1List.add(
            CarDetectChildBean(
                0,
                3,
                BaseApplication.instance.getString(R.string.abnormal_description4),
                BaseApplication.instance.getString(R.string.abnormal_item4),
                "40~60",
            ),
        )
        data1List.add(
            CarDetectChildBean(
                0,
                4,
                BaseApplication.instance.getString(R.string.abnormal_description5),
                BaseApplication.instance.getString(R.string.abnormal_item5),
                "40~60",
            ),
        )
        data1List.add(
            CarDetectChildBean(
                0,
                5,
                BaseApplication.instance.getString(R.string.abnormal_description6),
                BaseApplication.instance.getString(R.string.abnormal_item6),
                "40~60",
            ),
        )
        data1List.add(
            CarDetectChildBean(
                0,
                6,
                BaseApplication.instance.getString(R.string.abnormal_description7),
                BaseApplication.instance.getString(R.string.abnormal_item7),
                "40~60",
            ),
        )
        data1List.add(
            CarDetectChildBean(
                0,
                7,
                BaseApplication.instance.getString(R.string.abnormal_description8),
                BaseApplication.instance.getString(R.string.abnormal_item8),
                "80~100",
            ),
        )
        data1List.add(
            CarDetectChildBean(
                0,
                8,
                BaseApplication.instance.getString(R.string.abnormal_description9),
                BaseApplication.instance.getString(R.string.abnormal_item9),
                "80~100",
            ),
        )
        data1List.add(
            CarDetectChildBean(
                0,
                9,
                BaseApplication.instance.getString(R.string.abnormal_description10),
                BaseApplication.instance.getString(R.string.abnormal_item10),
                "80~100",
            ),
        )
        data1List.add(
            CarDetectChildBean(
                0,
                10,
                BaseApplication.instance.getString(R.string.abnormal_description11),
                BaseApplication.instance.getString(R.string.abnormal_item11),
                "80~100",
            ),
        )
        data1List.add(
            CarDetectChildBean(
                0,
                11,
                BaseApplication.instance.getString(R.string.abnormal_description12),
                BaseApplication.instance.getString(R.string.abnormal_item12),
                "80~100",
            ),
        )
        data1List.add(
            CarDetectChildBean(
                0,
                12,
                BaseApplication.instance.getString(R.string.abnormal_description13),
                BaseApplication.instance.getString(R.string.abnormal_item13),
                "80~100",
            ),
        )
        data2List.add(
            CarDetectChildBean(
                1,
                0,
                BaseApplication.instance.getString(R.string.abnormal_description14),
                BaseApplication.instance.getString(R.string.abnormal_item14),
                "20~50",
            ),
        )
        data2List.add(
            CarDetectChildBean(
                1,
                1,
                BaseApplication.instance.getString(R.string.abnormal_description15),
                BaseApplication.instance.getString(R.string.abnormal_item15),
                "20~50",
            ),
        )
        data2List.add(
            CarDetectChildBean(
                1,
                2,
                BaseApplication.instance.getString(R.string.abnormal_description16),
                BaseApplication.instance.getString(R.string.abnormal_item16),
                "20~50",
            ),
        )
        data2List.add(
            CarDetectChildBean(
                1,
                3,
                BaseApplication.instance.getString(R.string.abnormal_description17),
                BaseApplication.instance.getString(R.string.abnormal_item17),
                "20~50",
            ),
        )
        data2List.add(
            CarDetectChildBean(
                1,
                4,
                BaseApplication.instance.getString(R.string.abnormal_description18),
                BaseApplication.instance.getString(R.string.abnormal_item18),
                "20~50",
            ),
        )
        dataList.add(
            CarDetectBean(
                BaseApplication.instance.getString(R.string.abnormal_title1),
                data1List,
            ),
        )
        dataList.add(
            CarDetectBean(
                BaseApplication.instance.getString(R.string.abnormal_title2),
                data2List,
            ),
        )
        return dataList
    }
}
